"""Added new fields to FitnessProfile

Revision ID: a160655885e6
Revises: 29332bf4ab56
Create Date: 2023-07-29 16:43:26.589068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a160655885e6'
down_revision = '29332bf4ab56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_profile', schema=None) as batch_op:
        batch_op.alter_column('days_cant_train',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_profile', schema=None) as batch_op:
        batch_op.alter_column('days_cant_train',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
