"""empty message

Revision ID: 987dfe5bad11
Revises: 
Create Date: 2023-08-04 22:46:23.114470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987dfe5bad11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height_unit', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('weight_unit', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_profile', schema=None) as batch_op:
        batch_op.drop_column('weight_unit')
        batch_op.drop_column('height_unit')

    # ### end Alembic commands ###
